### ISSUE TITLE
Add docs of mathjax

### ISSUE THREAD

**Issue by maelle** [ropensci/dev_guide#199]
cf https://github.com/ropensci/rotemplate/pull/26

```yaml
template:
  params:
    mathjax: true
```

cc @Bisaloo
